# Generated by Django 4.2.5 on 2024-10-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0002_alter_author_bio_alter_author_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
